import type { Metadata } from "next";
import AuthProvider from "./AuthProvider";
import "./globals.css";
import AppBar from "./AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <AppBar />
          <div className={"min-h-srceen"}>
            {children}
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
