import Navbar from "@/components/nav/Navbar";
import AuthProvider from "@/components/AuthProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-100">
          <Navbar />
          <div>
            {children}
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
